### ISSUE TITLE
Lengthy processing time for 27kb .docx file

### ISSUE THREAD

**Issue by tballison** [trailofbits/polyfile#10]
Apache Tika's example of a .docx file with recursively embedded zip files takes roughly an hour to process.

I confirmed privately with a key committer that this is unexpected.

File is available here: https://github.com/apache/tika/blob/master/tika-server/src/test/resources/test_recursive_embedded.docx

**Comment by tballison** [comment]
This problem appears to be generalizable to at least ooxml (and possibly zip?) files generally.  I get similar performance on other "normal" .xlsx, .pptx and .docx in our unit test files on Apache Tika.

**Comment by ESultanik** [comment]
This should be resolved in `master` now and will be included in v0.3.0.
