### ISSUE TITLE
Weird Zip parsing in Evan's resume

### ISSUE THREAD

**Issue by angea** [trailofbits/polyfile#9]
It's pretty cool to have NES and PDF dissection of the polyglot resume, but what's with the weird ZIP structure?
![image](https://user-images.githubusercontent.com/5624411/68201482-24f0a600-ffc2-11e9-8280-8c2f73e80452.png)

Something went wrong:
![image](https://user-images.githubusercontent.com/5624411/68201630-6719e780-ffc2-11e9-837e-c7c82125a00c.png)

**Comment by ESultanik** [comment]
The multiple ZIP issue should be fixed by commit 6b86b2d91c9af19abc1520c1339935569b2cc964
